// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static double k_EncConvConst = 0.0010475;

    // Shooter motor constants
    public static double shooter_speed = 0.66;  // default
    public static double shooter_speed_fire = 0.92;  // shooting-specific
    // public static double shooter_speed_fire = 1.0;  // shooting-specific (West Valley)


    // Conveyor motor constants
    public static double conveyor_speed = 0.40;
    public static double conveyor_speed_fire = 1.0;
    
    // Handoff motor constants
    public static double handoff_speed = 0.75;
    public static double handoff_speed_fire = 0.75;
    
    // Intake motor constants
    public static double intake_speed = 0.80;
}