// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package robot;

import robot.commands.*;
import robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import robot.subsystems.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// The robot's subsystems
    public final effectsSubSys m_effectsSubSys = new effectsSubSys();
    public final cannonSubSys m_cannonSubSys = new cannonSubSys();
    public final drivetrainSubSys m_drivetrainSubSys = new drivetrainSubSys();

// Joysticks
private final Joystick driverJoystick = new Joystick(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems


    // SmartDashboard Buttons
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("fireCannonCmd", new fireCannonCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOnCmd", new compressorOnCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOffCmd", new compressorOffCmd( m_cannonSubSys ));
    SmartDashboard.putData("oogaHornCmd", new oogaHornCmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode1Cmd", new LEDMode1Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode2Cmd", new LEDMode2Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode3Cmd", new LEDMode3Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode4Cmd", new LEDMode4Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDOffCmd", new LEDOffCmd( m_effectsSubSys ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    // New way to put data on tabbed shuffleboard
    // Shuffleboard.getTab("user tab").add(myChooser);
    //
    //auto = new SendableChooser();
	//auto.addDefault(autoNone, new AutoNone());
	//auto.addObject(autoGearOnLeft, new AutoGearOnLeft());
	//auto.addObject(autoGearOnRight, new AutoGearOnRight());
	//auto.addObject(autoGearOnStraight, new AutoGearStrait());
	//SmartDashboard.putData("Auto modes", auto);

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons
final JoystickButton lEDOffBtn = new JoystickButton(driverJoystick, 9);        
lEDOffBtn.onTrue(new LEDOffCmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDOffBtn",new LEDOffCmd( m_effectsSubSys ) );

final JoystickButton lEDMode4Btn = new JoystickButton(driverJoystick, 6);        
lEDMode4Btn.onTrue(new LEDMode4Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode4Btn",new LEDMode4Cmd( m_effectsSubSys ) );

final JoystickButton lEDMode3Btn = new JoystickButton(driverJoystick, 5);        
lEDMode3Btn.onTrue(new LEDMode3Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode3Btn",new LEDMode3Cmd( m_effectsSubSys ) );

final JoystickButton lEDMode2Btn = new JoystickButton(driverJoystick, 4);        
lEDMode2Btn.onTrue(new LEDMode2Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode2Btn",new LEDMode2Cmd( m_effectsSubSys ) );

final JoystickButton lEDMode1Btn = new JoystickButton(driverJoystick, 3);        
lEDMode1Btn.onTrue(new LEDMode1Cmd( m_effectsSubSys ));
    SmartDashboard.putData("LEDMode1Btn",new LEDMode1Cmd( m_effectsSubSys ) );

final JoystickButton oogaHornBtn = new JoystickButton(driverJoystick, 11);        
oogaHornBtn.whileTrue(new oogaHornCmd( m_effectsSubSys ));
    SmartDashboard.putData("oogaHornBtn",new oogaHornCmd( m_effectsSubSys ) );

final JoystickButton compressorOffBtn = new JoystickButton(driverJoystick, 10);        
compressorOffBtn.onTrue(new compressorOffCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOffBtn",new compressorOffCmd( m_cannonSubSys ) );

final JoystickButton compressorOnBtn = new JoystickButton(driverJoystick, 8);        
compressorOnBtn.onTrue(new compressorOnCmd( m_cannonSubSys ));
    SmartDashboard.putData("compressorOnBtn",new compressorOnCmd( m_cannonSubSys ) );

final JoystickButton fireCannonBtn = new JoystickButton(driverJoystick, 2);        
fireCannonBtn.onTrue(new fireCannonCmd( m_cannonSubSys ));
    SmartDashboard.putData("fireCannonBtn",new fireCannonCmd( m_cannonSubSys ) );

final JoystickButton driveByJoystickBtn = new JoystickButton(driverJoystick, 1);        
driveByJoystickBtn.onTrue(new driveByJoystickCmd( m_drivetrainSubSys ));
    SmartDashboard.putData("driveByJoystickBtn",new driveByJoystickCmd( m_drivetrainSubSys ) );



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public Joystick getdriverJoystick() {
        return driverJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

